kind: Service
apiVersion: v1
metadata:
  name: web_server-service
spec:
  type: NodePort
  selector:
    app: web_server
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web_server-deployment
  labels:
    app: web_server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web_server
  template:
    metadata:
      labels:
        app: web_server
    spec:
      containers:
      - name: web_server
        image: st251/web_server:${env.BUILD_NUMBER}
        ports:
        - containerPort: 8080
